### ISSUE TITLE
PyNEC installation via pip fails

### ISSUE THREAD

**Issue by dl2sen** [tmolteno/python-necpp#31]
Hallo,

trying to install PyNEC via pip on a Ubuntu 24.04 within a venv yields following outcome. The message confuses me, since numpy is definetely installed.

Any help from you would be appreciated.

Oli

Collecting pynec
  Using cached PyNEC-1.7.3.6.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/oliver/workspace/venv/rf/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/oliver/workspace/venv/rf/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/oliver/workspace/venv/rf/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ldmo24kb/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-ldmo24kb/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ldmo24kb/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ldmo24kb/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by myzinsky** [comment]
Same issue here, also with `uv`

**Comment by konstantgr** [comment]
Hi! I've recently got the same problem. 

The updating wheel package via
```bash
pip install --upgrade wheel
```
solved my problem for `PyNEC==1.7.3.4` version. I've tried it on Python 3.11.

**Comment by khm1234** [comment]
Looks like I have the same problem -- "no module named numpy."   I've checked (multiple ways) and numpy is installed.
"pip install --upgrade wheel" did not fix it for me.

Python version 3.13.5.   OSX 15.7.4.
